### ISSUE TITLE
Communicating with Kafka

### ISSUE THREAD

**Issue by nikhilbiyani** [DMSC-Instrument-Data/ecp-backlog#2]
NICOS needs to talk to Kafa (send and receive messages). The use cases are:

- NICOS needs to configure the EPICS to Kafka forwarder
- NICOS needs to control the NeXus file writer.
- NICOS may need to stream data to Kafka for file writing
- NICOS will need to interact with the online data reduction via Kafka.

For this Kafka device mixins that can act as consumers and producers have to be created.

**Comment by MikeHart85** [comment]
@OwenArnold and I were discussing this:

It would be good to know what the use cases are that support these points. For example, we aren't clear on what exactly the third point means.

**Comment by nikhilbiyani** [comment]
So the basic theme here is that we would need to communicate with Kafka. The most basic example is: issuing command to forwards some epics pvs to Kafka using (https://github.com/ess-dmsc/forward-epics-to-kafka) and to issue commands to start dumping things in file from Kafka (https://github.com/ess-dmsc/kafka-to-nexus). For this one would need to write a command in JSON format to one of the Kafka topics and read back some logs or error messages from another topic which (probably) should be displayed somewhere in NICOS. 

There can also be transactions which involve other things than issuing commands. For example, encoding the status information to a topic (this might not come directly from a PV and can be calculated in a NICOS device class). This information  might also be needed by the file writer.

**Comment by mkoennecke** [comment]
Regarding the third point: 

Consider a movement in Q which involves running multiple physical motors. While this is moving one might want to stream intermediate Q values from NICOS. This is one example, there may be other instances of data items residing in NICOS which may need to be streamed

**Comment by OwenArnold** [comment]
@nikhilbiyani is the kanban board for this stale? Can you link to the code changes?

**Comment by nikhilbiyani** [comment]
NICOS changes:
https://forge.frm2.tum.de/review/#/c/16648/

**Comment by mattclarke** [comment]
Moved to JIRA https://jira.esss.lu.se/browse/DM-703
