### ISSUE TITLE
Changing NICOS cache daemon to use Kafka

### ISSUE THREAD

**Issue by nikhilbiyani** [DMSC-Instrument-Data/ecp-backlog#4]
Once Kafka can store all the data, it would make sense to change the current cache daemon and optimize it such that it uses data from Kafka. Before doing this NICOS should be able to decode the serialized data using flatbuffers.

**Comment by nikhilbiyani** [comment]
Changes:
https://forge.frm2.tum.de/review/#/c/16295/
https://forge.frm2.tum.de/review/#/c/16375/

**Comment by mattclarke** [comment]
Moved to JIRA https://jira.esss.lu.se/browse/DM-701
